function additionner() {
    const A = document.getElementById('A').value;
    const B = document.getElementById('B').value;
    const C = document.getElementById('C').value;
    const D = document.getElementById('D').value;
    const E = document.getElementById('E').value;
    const F = document.getElementById('F').value;
    const resultat = parseInt(A) + parseInt(B) + parseInt(C) + parseInt(D) + parseInt(E) + parseInt(F);
    document.getElementById('resultat').textContent = resultat;
}
document.addEventListener('DOMContentLoaded', () => {
    const A = document.getElementById('A');
    const B = document.getElementById('B');
    const C = document.getElementById('C');
    const D = document.getElementById('D');
    const E = document.getElementById('E');
    const F = document.getElementById('F');
    // const G = document.getElementById('G');
    // const H = document.getElementById('H');
    //  const I = document.getElementById('I');
    const B1 = document.getElementById('B1');
    const B2 = document.getElementById('B2');
    const B3 = document.getElementById('B3');
    const B4 = document.getElementById('B4');
    const B5 = document.getElementById('B5');
    const B6 = document.getElementById('B6');
    const B7 = document.getElementById('B7');
    const B8 = document.getElementById('B8');
    const B9 = document.getElementById('B9');
    const B10 = document.getElementById('B10');
    const B11 = document.getElementById('B11');
    const B12 = document.getElementById('B12');
    const B13 = document.getElementById('B13');
    const B14 = document.getElementById('B14');
    const B15 = document.getElementById('B15');
    const B16 = document.getElementById('B16');
    const B17 = document.getElementById('B17');
    const B18 = document.getElementById('B18');
    const B19 = document.getElementById('B19');
    const B20 = document.getElementById('B20');
    const B21 = document.getElementById('B21');

    const D1 = document.getElementById('D1');
    const D2 = document.getElementById('D2');
    const D3 = document.getElementById('D3');
    const D4 = document.getElementById('D4');
    const D5 = document.getElementById('D5');
    const D6 = document.getElementById('D6');
    const D7 = document.getElementById('D7');
    const D8 = document.getElementById('D8');
    const D9 = document.getElementById('D9');
    const D10 = document.getElementById('D10');
    const D11 = document.getElementById('D11');
    const D12 = document.getElementById('D12');
    const D13 = document.getElementById('D13');
    const D14 = document.getElementById('D14');
    const D15 = document.getElementById('D15');
    const D16 = document.getElementById('D16');
    const D17 = document.getElementById('D17');
    const D18 = document.getElementById('D18');
    const D19 = document.getElementById('D19');
    const D20 = document.getElementById('D20');
    const D21 = document.getElementById('D21');


    function calculer() {
        const aValue = parseFloat(A.value);
        const bValue = parseFloat(B.value);
        const cValue = parseFloat(C.value);
        const dValue = parseFloat(D.value);
        const eValue = parseFloat(E.value);
        const fValue = parseFloat(F.value);
        //  const gValue = parseFloat(G.value);
        //  const hValue = parseFloat(H.value);
        //   const iValue = parseFloat(I.value);
        const b1Value = parseFloat(B1.value) / 100;
        const b2Value = parseFloat(B2.value) / 100;
        const b3Value = parseFloat(B3.value) / 100;
        const b4Value = parseFloat(B4.value) / 100;
        const b5Value = parseFloat(B5.value) / 100;
        const b6Value = parseFloat(B6.value) / 100;
        const b7Value = parseFloat(B7.value) / 100;
        const b8Value = parseFloat(B8.value) / 100;
        const b9Value = parseFloat(B9.value) / 100;
        const b10Value = parseFloat(B10.value) / 100;
        const b11Value = parseFloat(B11.value) / 100;
        const b12Value = parseFloat(B12.value) / 100;
        const b13Value = parseFloat(B13.value) / 100;
        const b14Value = parseFloat(B14.value) / 100;
        const b15Value = parseFloat(B15.value) / 100;
        const b16Value = parseFloat(B16.value) / 100;
        const b17Value = parseFloat(B17.value) / 100;
        const b18Value = parseFloat(B18.value) / 100;
        const b19Value = parseFloat(B19.value) / 100;
        const b20Value = parseFloat(B20.value) / 100;
        const b21Value = parseFloat(B21.value) / 100;
        // const b22Value = parseFloat(B22.value) / 100;
        //  const b23Value = parseFloat(B23.value) / 100;
        //  const b24Value = parseFloat(B24.value) / 100;
        //  const b25Value = parseFloat(B25.value) / 100;
        //  const b26Value = parseFloat(B26.value) / 100;
        //  const b27Value = parseFloat(B27.value) / 100;
        //  const b28Value = parseFloat(B28.value) / 100;
        // const b29Value = parseFloat(B29.value) / 100;
        //  const b30Value = parseFloat(B30.value) / 100;
        const resultB1 = aValue * b1Value;
        const resultB2 = aValue * b2Value;
        const resultB3 = aValue * b3Value;
        const resultB4 = aValue * b4Value;
        const resultB5 = bValue * b5Value;
        const resultB6 = bValue * b6Value;
        const resultB7 = bValue * b7Value;
        const resultB8 = bValue * b8Value;
        const resultB9 = bValue * b9Value;
        const resultB10 = cValue * b10Value;
        const resultB11 = cValue * b11Value;
        const resultB12 = cValue * b12Value;
        const resultB13 = dValue * b13Value;
        const resultB14 = dValue * b14Value;
        const resultB15 = dValue * b15Value;
        const resultB16 = eValue * b16Value;
        const resultB17 = eValue * b17Value;
        const resultB18 = eValue * b18Value;
        const resultB19 = fValue * b19Value;
        const resultB20 = fValue * b20Value;
        const resultB21 = fValue * b21Value;
        // const resultB22 = gValue * b22Value;
        //const resultB23 = gValue * b23Value;
        //const resultB24 = gValue * b24Value;
        //  const resultB25 = hValue * b25Value;
        //  const resultB26 = hValue * b26Value;
        //  const resultB27 = hValue * b27Value;
        //  const resultB28 = iValue * b28Value;
        //  const resultB29 = iValue * b29Value;
        // const resultB30 = iValue * b30Value;
        D1.textContent = resultB1.toFixed(2);
        D2.textContent = resultB2.toFixed(2);
        D3.textContent = resultB3.toFixed(2);
        D4.textContent = resultB4.toFixed(2);
        D5.textContent = resultB5.toFixed(2);
        D6.textContent = resultB6.toFixed(2);
        D7.textContent = resultB7.toFixed(2);
        D8.textContent = resultB8.toFixed(2);
        D9.textContent = resultB9.toFixed(2);
        D10.textContent = resultB10.toFixed(2);
        D11.textContent = resultB11.toFixed(2);
        D12.textContent = resultB12.toFixed(2);
        D13.textContent = resultB13.toFixed(2);
        D14.textContent = resultB14.toFixed(2);
        D15.textContent = resultB15.toFixed(2);
        D16.textContent = resultB16.toFixed(2);
        D17.textContent = resultB17.toFixed(2);
        D18.textContent = resultB18.toFixed(2);
        D19.textContent = resultB19.toFixed(2);
        D20.textContent = resultB20.toFixed(2);
        D21.textContent = resultB21.toFixed(2);

        function calculerTempsRestant25(result, element) {
            const tempsRestantHeures = 25 / result;
            const heures = Math.floor(tempsRestantHeures);
            const minutes = Math.round((tempsRestantHeures - heures) * 60);
            const tempsAffichage = isNaN(heures) || isNaN(minutes) ? "-" : heures + "h" + minutes + "m";
            element.textContent = tempsAffichage;
        }
        function calculerTempsRestant24(result, element) {
            const tempsRestantHeures = 24 / result;
            const heures = Math.floor(tempsRestantHeures);
            const minutes = Math.round((tempsRestantHeures - heures) * 60);
            const tempsAffichage = isNaN(heures) || isNaN(minutes) ? "-" : heures + "h" + minutes + "m";
            element.textContent = tempsAffichage;
        }
        calculerTempsRestant25(resultB1, E1);
        calculerTempsRestant24(resultB2, E2);
        calculerTempsRestant24(resultB3, E3);
        calculerTempsRestant24(resultB4, E4);
        calculerTempsRestant24(resultB5, E5);
        calculerTempsRestant24(resultB6, E6);
        calculerTempsRestant24(resultB7, E7);
        calculerTempsRestant24(resultB8, E8);
        calculerTempsRestant24(resultB9, E9);
        calculerTempsRestant24(resultB10, E10);
        calculerTempsRestant24(resultB11, E11);
        calculerTempsRestant24(resultB12, E12);
        calculerTempsRestant24(resultB13, E13);
        calculerTempsRestant24(resultB14, E14);
        calculerTempsRestant24(resultB15, E15);
        calculerTempsRestant24(resultB16, E16);
        calculerTempsRestant24(resultB17, E17);
        calculerTempsRestant24(resultB18, E18);
        calculerTempsRestant24(resultB19, E19);
        calculerTempsRestant24(resultB20, E20);
        calculerTempsRestant24(resultB21, E21);
        calculerTempsRestant24(resultB22, E22);
        calculerTempsRestant24(resultB23, E23);
        calculerTempsRestant24(resultB24, E24);
        calculerTempsRestant24(resultB25, E25);
        calculerTempsRestant24(resultB26, E26);
        calculerTempsRestant24(resultB27, E27);
        calculerTempsRestant24(resultB28, E28);
        calculerTempsRestant24(resultB29, E29);
        calculerTempsRestant24(resultB30, E30);
    }
    A.addEventListener('input', calculer);
    B.addEventListener('input', calculer);
    C.addEventListener('input', calculer);
    D.addEventListener('input', calculer);
    E.addEventListener('input', calculer);
    F.addEventListener('input', calculer);
    // G.addEventListener('input', calculer);
    // H.addEventListener('input', calculer);
    // I.addEventListener('input', calculer);
    B1.addEventListener('input', calculer);
    B2.addEventListener('input', calculer);
    B3.addEventListener('input', calculer);
    B4.addEventListener('input', calculer);
    B5.addEventListener('input', calculer);
    B6.addEventListener('input', calculer);
    B7.addEventListener('input', calculer);
    B8.addEventListener('input', calculer);
    B9.addEventListener('input', calculer);
    B10.addEventListener('input', calculer);
    B11.addEventListener('input', calculer);
    B12.addEventListener('input', calculer);
    B13.addEventListener('input', calculer);
    B14.addEventListener('input', calculer);
    B15.addEventListener('input', calculer);
    B16.addEventListener('input', calculer);
    B17.addEventListener('input', calculer);
    B18.addEventListener('input', calculer);
    B19.addEventListener('input', calculer);
    B20.addEventListener('input', calculer);
    B21.addEventListener('input', calculer);
    B22.addEventListener('input', calculer);
    B23.addEventListener('input', calculer);
    B24.addEventListener('input', calculer);
    B25.addEventListener('input', calculer);
    B26.addEventListener('input', calculer);
    B27.addEventListener('input', calculer);
    B28.addEventListener('input', calculer);
    B29.addEventListener('input', calculer);
    B30.addEventListener('input', calculer);

});
document.addEventListener('DOMContentLoaded', () => {
    const a1 = document.getElementById('a1');
    const f1 = document.getElementById('f1');
    const a2 = document.getElementById('a2');
    const f2 = document.getElementById('f2');
    const a3 = document.getElementById('a3');
    const f3 = document.getElementById('f3');
    const a4 = document.getElementById('a4');
    const f4 = document.getElementById('f4');
    const a5 = document.getElementById('a5');
    const f5 = document.getElementById('f5');
    const a6 = document.getElementById('a6');
    const f6 = document.getElementById('f6');
    const a7 = document.getElementById('a7');
    const f7 = document.getElementById('f7');
    const a8 = document.getElementById('a8');
    const f8 = document.getElementById('f8');
    const a9 = document.getElementById('a9');
 const f9 = document.getElementById('f9');
    const a10 = document.getElementById('a10');
     const f10 = document.getElementById('f10');
    const a11 = document.getElementById('a11');
    const f11 = document.getElementById('f11');
    const a12 = document.getElementById('a12');
    const f12 = document.getElementById('f12');
     const a13 = document.getElementById('a13');
    const f13 = document.getElementById('f13');
    const a14 = document.getElementById('a14');
 const f14 = document.getElementById('f14');
      const a15 = document.getElementById('a15');
     const f15 = document.getElementById('f15');
     const a16 = document.getElementById('a16');
      const f16 = document.getElementById('f16');
      const a17 = document.getElementById('a17');
      const f17 = document.getElementById('f17');
     const a18 = document.getElementById('a18');
      const f18 = document.getElementById('f18');
     const a19 = document.getElementById('a19');
       const f19 = document.getElementById('f19');
       const a20 = document.getElementById('a20');
      const f20 = document.getElementById('f20');
      const a21 = document.getElementById('a21');
     const f21 = document.getElementById('f21');
    //  const a22 = document.getElementById('a22');
    //  const f22 = document.getElementById('f22');
    //  const a23 = document.getElementById('a23');
    //  const f23 = document.getElementById('f23');
    //  const a24 = document.getElementById('a24');
    //  const f24 = document.getElementById('f24');
    //  const a25 = document.getElementById('a25');
    //  const f25 = document.getElementById('f25');
    //  const a26 = document.getElementById('a26');
    //  const f26 = document.getElementById('f26');
    //  const a27 = document.getElementById('a27');
    //  const f27 = document.getElementById('f27');
    //  const a28 = document.getElementById('a28');
    //  const f28 = document.getElementById('f28');
    //  const a29 = document.getElementById('a29');
    //  const f29 = document.getElementById('f29');
    //  const a30 = document.getElementById('a30');
    //  const f30 = document.getElementById('f30');

    function compareAndStyle(element1, element2, rowNumber) {
        // Sélectionner tous les td de la ligne sauf ceux avec rowspan
        const row = element1.closest('tr');
        const cells = row.querySelectorAll('td:not([rowspan])');
        
        if (element1.value !== element2.value) {
            // Ajouter la classe à toutes les cellules de la ligne
            cells.forEach(cell => {
                cell.classList.add('different');
                // S'assurer que les inputs dans les cellules sont aussi colorés
                const inputs = cell.querySelectorAll('input');
                inputs.forEach(input => input.classList.add('different'));
            });
        } else {
            // Retirer la classe de toutes les cellules de la ligne
            cells.forEach(cell => {
                cell.classList.remove('different');
                // Retirer la classe des inputs
                const inputs = cell.querySelectorAll('input');
                inputs.forEach(input => input.classList.remove('different'));
            });
        }
    }

    compareAndStyle(a1, f1);
    compareAndStyle(a2, f2);
    compareAndStyle(a3, f3);
    compareAndStyle(a4, f4);
    compareAndStyle(a5, f5);
    compareAndStyle(a6, f6);
    //compareAndStyle(a7, f7);
    //compareAndStyle(a8, f8);
    //compareAndStyle(a9, f9);
    //compareAndStyle(a10, f10);
    //compareAndStyle(a11, f11);
    //compareAndStyle(a12, f12);
   // compareAndStyle(a13, f13);
    //compareAndStyle(a14, f14);
   //  compareAndStyle(a15, f15);
   //  compareAndStyle(a16, f16);
   // compareAndStyle(a17, f17);
   // compareAndStyle(a18, f18);
    //  compareAndStyle(a19, f19);
    //  compareAndStyle(a20, f20);
   //   compareAndStyle(a21, f21);
    //  compareAndStyle(a22, f22);
    //  compareAndStyle(a23, f23);
    //  compareAndStyle(a24, f24);
    //  compareAndStyle(a25, f25);
    //  compareAndStyle(a26, f26);
    // compareAndStyle(a27, f27);
    //  compareAndStyle(a28, f28);
    //  compareAndStyle(a29, f29);
    //  compareAndStyle(a30, f30);


    a1.addEventListener('input', () => compareAndStyle(a1, f1));
    f1.addEventListener('input', () => compareAndStyle(a1, f1));
    a2.addEventListener('input', () => compareAndStyle(a2, f2));
    f2.addEventListener('input', () => compareAndStyle(a2, f2));
    a3.addEventListener('input', () => compareAndStyle(a3, f3));
    f3.addEventListener('input', () => compareAndStyle(a3, f3));
    a4.addEventListener('input', () => compareAndStyle(a4, f4));
    f4.addEventListener('input', () => compareAndStyle(a4, f4));
    a5.addEventListener('input', () => compareAndStyle(a5, f5));
    f5.addEventListener('input', () => compareAndStyle(a5, f5));
    a6.addEventListener('input', () => compareAndStyle(a6, f6));
    f6.addEventListener('input', () => compareAndStyle(a6, f6));
    a7.addEventListener('input', () => compareAndStyle(a7, f7));
    f7.addEventListener('input', () => compareAndStyle(a7, f7));
    a8.addEventListener('input', () => compareAndStyle(a8, f8));
    f8.addEventListener('input', () => compareAndStyle(a8, f8));
    a9.addEventListener('input', () => compareAndStyle(a9, f9));
    f9.addEventListener('input', () => compareAndStyle(a9, f9));
    a10.addEventListener('input', () => compareAndStyle(a10, f10));
    f10.addEventListener('input', () => compareAndStyle(a10, f10));
    a11.addEventListener('input', () => compareAndStyle(a11, f11));
    f11.addEventListener('input', () => compareAndStyle(a11, f11));
    a12.addEventListener('input', () => compareAndStyle(a12, f12));
    f12.addEventListener('input', () => compareAndStyle(a12, f12));
    a13.addEventListener('input', () => compareAndStyle(a13, f13));
    f13.addEventListener('input', () => compareAndStyle(a13, f13));
    a14.addEventListener('input', () => compareAndStyle(a14, f14));
    f14.addEventListener('input', () => compareAndStyle(a14, f14));
    a15.addEventListener('input', () => compareAndStyle(a15, f15));
    f15.addEventListener('input', () => compareAndStyle(a15, f15));
    a16.addEventListener('input', () => compareAndStyle(a16, f16));
    f16.addEventListener('input', () => compareAndStyle(a16, f16));
    a17.addEventListener('input', () => compareAndStyle(a17, f17));
    f17.addEventListener('input', () => compareAndStyle(a17, f17));
    a18.addEventListener('input', () => compareAndStyle(a18, f18));
    f18.addEventListener('input', () => compareAndStyle(a18, f18));
    a19.addEventListener('input', () => compareAndStyle(a19, f19));
    f19.addEventListener('input', () => compareAndStyle(a19, f19));
    a20.addEventListener('input', () => compareAndStyle(a20, f20));
    f20.addEventListener('input', () => compareAndStyle(a20, f20));
    a21.addEventListener('input', () => compareAndStyle(a21, f21));
    f21.addEventListener('input', () => compareAndStyle(a21, f21));
    a22.addEventListener('input', () => compareAndStyle(a22, f22));
    f22.addEventListener('input', () => compareAndStyle(a22, f22));
    a23.addEventListener('input', () => compareAndStyle(a23, f23));
    f23.addEventListener('input', () => compareAndStyle(a23, f23));
    a24.addEventListener('input', () => compareAndStyle(a24, f24));
    f24.addEventListener('input', () => compareAndStyle(a24, f24));
    a25.addEventListener('input', () => compareAndStyle(a25, f25));
    f25.addEventListener('input', () => compareAndStyle(a25, f25));
    a26.addEventListener('input', () => compareAndStyle(a26, f26));
    f26.addEventListener('input', () => compareAndStyle(a26, f26));
    a27.addEventListener('input', () => compareAndStyle(a27, f27));
    f27.addEventListener('input', () => compareAndStyle(a27, f27));
    a28.addEventListener('input', () => compareAndStyle(a28, f28));
    f28.addEventListener('input', () => compareAndStyle(a28, f28));
    a29.addEventListener('input', () => compareAndStyle(a29, f29));
    f29.addEventListener('input', () => compareAndStyle(a29, f29));
    a30.addEventListener('input', () => compareAndStyle(a30, f30));
    f30.addEventListener('input', () => compareAndStyle(a30, f30));



});





